################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_address_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_destroy.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_reset.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_stall.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_status.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_frame_number_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_function.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_initialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_initialize_complete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_state_change.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_abort.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_request.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_activate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_change.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_deactivate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_entry.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_initialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_read.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_read_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_thread.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_write.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_write_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_alternate_setting_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_alternate_setting_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_class_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_class_unregister.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_clear_feature.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_configuration_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_configuration_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_control_request_process.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_descriptor_send.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_disconnect.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_endpoint_stall.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_get_status.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_host_wakeup.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_initialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_start.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_microsoft_extension_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_set_feature.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_tasks_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_abort.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_all_request_abort.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_request.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_uninitialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynch_queue_process.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynch_schedule.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynchronous_endpoint_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynchronous_endpoint_destroy.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_controller_disable.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_ed_obtain.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_ed_td_clean.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_endpoint_reset.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_entry.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_frame_number_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_frame_number_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_initialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_interrupt_endpoint_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_iso_queue_process.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_iso_schedule.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_isochronous_endpoint_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_isochronous_td_obtain.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_least_traffic_list_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_endpoint_destroy.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_schedule.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_tree_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_port_reset.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_port_status_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_regular_td_obtain.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_bulk_transfer.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_control_transfer.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_interupt_transfer.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_isochronous_transfer.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_transfer.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_timer_function.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transaction_schedule.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transfer_abort.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transfer_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_uninitialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_activate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_configure.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_deactivate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_endpoints_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_entry.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_ioctl.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_read.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_write.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_check.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_claim.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_release.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_call.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_device_scan.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_destroy.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_verify.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_interface_scan.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_unregister.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_descriptor_parse.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_enumerate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_instance_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_instance_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_interface_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_interface_scan.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_delay_ms.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_address_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_activate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_deactivate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_reset.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_select.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_descriptor_read.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_remove.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_resources_free.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_instance_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_instance_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_reset.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_transfer_abort.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_enum_thread_entry.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_thread_entry.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_transfer_request.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_unregister.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hnp_polling_thread_entry.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_initialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_endpoint_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_instance_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_instance_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_setting_select.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interfaces_scan.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_configuration_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_device_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_device_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_endpoint_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_interface_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_change_process.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_device_extraction.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_device_insertion.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_role_swap.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_tasks_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_request.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_request_abort.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_uninitialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_error_handler.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_initialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_tasks_run.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_uninitialize.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_event_insert.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_event_update.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_object_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_object_unregister.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_debug_callback_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_debug_log.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_delay_ms.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_descriptor_pack.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_descriptor_parse.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_error_callback_register.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_get_big_endian.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_put.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_put_big_endian.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_add_safe.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_mulc_safe.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_mulv_safe.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_compare.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_copy.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_free.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_free_block_best_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_set.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_off.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_on.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_class_scan.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_read.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_write.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_physical_address.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_put.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_set_interrupt_handler.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_get_big_endian.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_put.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_put_big_endian.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_length_check.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_length_get.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_to_unicode.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_identify.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_relinquish.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_resume.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_schedule_other.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_sleep.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_suspend.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_timer_create.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_timer_delete.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_unicode_to_string.c \
../ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_virtual_address.c 

C_DEPS += \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_address_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_destroy.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_reset.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_stall.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_status.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_frame_number_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_function.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_initialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_initialize_complete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_state_change.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_abort.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_request.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_activate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_change.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_deactivate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_entry.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_initialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_read.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_read_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_thread.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_write.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_write_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_alternate_setting_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_alternate_setting_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_class_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_class_unregister.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_clear_feature.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_configuration_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_configuration_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_control_request_process.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_descriptor_send.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_disconnect.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_endpoint_stall.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_get_status.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_host_wakeup.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_initialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_start.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_microsoft_extension_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_set_feature.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_tasks_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_abort.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_all_request_abort.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_request.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_uninitialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynch_queue_process.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynch_schedule.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynchronous_endpoint_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynchronous_endpoint_destroy.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_controller_disable.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_ed_obtain.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_ed_td_clean.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_endpoint_reset.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_entry.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_frame_number_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_frame_number_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_initialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_interrupt_endpoint_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_iso_queue_process.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_iso_schedule.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_isochronous_endpoint_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_isochronous_td_obtain.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_least_traffic_list_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_endpoint_destroy.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_schedule.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_tree_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_port_reset.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_port_status_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_regular_td_obtain.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_bulk_transfer.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_control_transfer.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_interupt_transfer.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_isochronous_transfer.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_transfer.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_timer_function.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transaction_schedule.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transfer_abort.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transfer_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_uninitialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_activate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_configure.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_deactivate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_endpoints_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_entry.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_ioctl.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_read.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_write.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_check.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_claim.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_release.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_call.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_device_scan.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_destroy.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_verify.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_interface_scan.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_unregister.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_descriptor_parse.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_enumerate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_instance_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_instance_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_interface_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_interface_scan.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_delay_ms.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_address_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_activate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_deactivate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_reset.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_select.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_descriptor_read.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_remove.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_resources_free.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_instance_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_instance_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_reset.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_transfer_abort.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_enum_thread_entry.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_thread_entry.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_transfer_request.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_unregister.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hnp_polling_thread_entry.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_initialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_endpoint_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_instance_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_instance_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_setting_select.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interfaces_scan.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_configuration_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_device_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_device_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_endpoint_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_interface_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_change_process.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_device_extraction.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_device_insertion.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_role_swap.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_tasks_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_request.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_request_abort.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_uninitialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_error_handler.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_initialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_tasks_run.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_uninitialize.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_event_insert.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_event_update.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_object_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_object_unregister.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_debug_callback_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_debug_log.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_delay_ms.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_descriptor_pack.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_descriptor_parse.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_error_callback_register.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_get_big_endian.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_put.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_put_big_endian.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_add_safe.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_mulc_safe.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_mulv_safe.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_compare.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_copy.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_free.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_free_block_best_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_set.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_off.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_on.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_class_scan.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_read.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_write.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_physical_address.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_put.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_set_interrupt_handler.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_get_big_endian.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_put.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_put_big_endian.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_length_check.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_length_get.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_to_unicode.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_identify.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_relinquish.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_resume.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_schedule_other.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_sleep.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_suspend.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_timer_create.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_timer_delete.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_unicode_to_string.d \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_virtual_address.d 

OBJS += \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_address_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_destroy.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_reset.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_stall.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_endpoint_status.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_frame_number_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_function.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_initialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_initialize_complete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_state_change.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_abort.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_request.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_dcd_sim_slave_transfer_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_activate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_change.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_deactivate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_entry.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_initialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_read.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_read_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_thread.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_write.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_class_dpump_write_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_alternate_setting_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_alternate_setting_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_class_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_class_unregister.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_clear_feature.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_configuration_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_configuration_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_control_request_process.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_descriptor_send.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_disconnect.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_endpoint_stall.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_get_status.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_host_wakeup.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_initialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_interface_start.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_microsoft_extension_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_set_feature.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_tasks_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_abort.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_all_request_abort.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_request.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_transfer_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_device_stack_uninitialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynch_queue_process.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynch_schedule.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynchronous_endpoint_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_asynchronous_endpoint_destroy.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_controller_disable.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_ed_obtain.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_ed_td_clean.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_endpoint_reset.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_entry.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_frame_number_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_frame_number_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_initialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_interrupt_endpoint_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_iso_queue_process.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_iso_schedule.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_isochronous_endpoint_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_isochronous_td_obtain.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_least_traffic_list_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_endpoint_destroy.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_schedule.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_periodic_tree_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_port_reset.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_port_status_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_regular_td_obtain.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_bulk_transfer.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_control_transfer.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_interupt_transfer.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_isochronous_transfer.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_request_transfer.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_timer_function.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transaction_schedule.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transfer_abort.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_transfer_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_hcd_sim_host_uninitialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_activate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_configure.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_deactivate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_endpoints_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_entry.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_ioctl.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_read.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_class_dpump_write.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_check.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_claim.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_bandwidth_release.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_call.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_device_scan.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_destroy.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_instance_verify.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_interface_scan.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_class_unregister.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_descriptor_parse.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_enumerate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_instance_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_instance_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_interface_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_interface_scan.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_configuration_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_delay_ms.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_address_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_activate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_deactivate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_reset.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_configuration_select.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_descriptor_read.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_remove.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_device_resources_free.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_instance_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_instance_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_reset.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_endpoint_transfer_abort.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_enum_thread_entry.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_thread_entry.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_transfer_request.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hcd_unregister.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_hnp_polling_thread_entry.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_initialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_endpoint_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_instance_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_instance_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interface_setting_select.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_interfaces_scan.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_configuration_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_device_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_device_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_endpoint_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_new_interface_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_change_process.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_device_extraction.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_rh_device_insertion.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_role_swap.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_tasks_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_request.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_request_abort.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_transfer_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_host_stack_uninitialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_error_handler.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_initialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_tasks_run.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_system_uninitialize.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_event_insert.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_event_update.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_object_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_trace_object_unregister.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_debug_callback_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_debug_log.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_delay_ms.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_descriptor_pack.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_descriptor_parse.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_error_callback_register.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_event_flags_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_get_big_endian.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_put.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_long_put_big_endian.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_add_safe.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_mulc_safe.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_allocate_mulv_safe.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_compare.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_copy.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_free.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_free_block_best_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_memory_set.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_off.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_mutex_on.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_class_scan.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_read.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_pci_write.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_physical_address.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_semaphore_put.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_set_interrupt_handler.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_get_big_endian.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_put.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_short_put_big_endian.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_length_check.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_length_get.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_string_to_unicode.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_identify.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_relinquish.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_resume.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_schedule_other.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_sleep.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_thread_suspend.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_timer_create.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_timer_delete.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_unicode_to_string.o \
./ra/microsoft/azure-rtos/usbx/common/core/src/ux_utility_virtual_address.o 


# Each subdirectory must supply rules for building sources it contributes
ra/microsoft/azure-rtos/usbx/common/core/src/%.o: ../ra/microsoft/azure-rtos/usbx/common/core/src/%.c
	$(file > $@.in,-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal  -g -D_RENESAS_RA_ -DUSB_CFG_PCDC_USE -DADD_USB_RNDIS_MODIFIED -D_RA_CORE=CM4 -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/src" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/src/ux_device_class_rndis_src" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/src/ux_network_driver_src" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/inc" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/inc/api" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/inc/instances" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/src/rm_threadx_port" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/threadx/common/inc" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/arm/CMSIS_5/CMSIS/Core/Include" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_gen" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/fsp_cfg/bsp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/fsp_cfg" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/fsp_cfg/azure/tx" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/src/r_usb_basic/src/driver/inc" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/src/rm_usbx_port" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/inc/ports" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/filex/common/inc" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/fsp/src/rm_netxduo_ether" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/pop3" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/snmp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/nat" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/mqtt" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/ftp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/tftp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/sntp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/smtp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/web" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/auto_ip" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/telnet" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/dns" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/dhcp" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/http" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/common/inc" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/ports/cortex_m4" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/netxduo/addons/cloud" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/fsp_cfg/azure/fx" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/ra_gen" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/fsp_cfg/middleware" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra_cfg/fsp_cfg/azure/nxd" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/usbx/common/usbx_device_classes/inc" -I"C:/Users/alex/e2_studio/workspace/rndis/USBX Device RNDIS on RA POC/USBX Device RNDIS on RA POC/azure_usbx_device_rndis_ep_ek_ra6m5/ra/microsoft/azure-rtos/usbx/common/core/inc" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

